"""UniPulse 种子数据 - 120所全球高校（全面覆盖）"""
from datetime import datetime

now = datetime.now().strftime('%Y-%m-%d %H:%M')

def m(academic,employer,ratio,international,citations,research,teaching,employment):
    return {"academic":academic,"employer":employer,"ratio":ratio,"international":international,"citations":citations,"research":research,"teaching":teaching,"employment":employment}

def t(text,typ): return {"text":text,"type":typ}

# ==================== 北美（美国+加拿大） ====================
NA_UNIS = [
    {"id":1,"name":"Harvard University","cn":"哈佛大学","loc":"美国","region":"北美","country":"美国","logo":"#A51D2D","initials":"H","score":97.5,"trend":"up","trendV":"+0.3","stars":4.9,"reviews":2841,"rank":1,"metrics":m(98,97,82,95,97,97,88,97),"tags":[t("藤校","purple"),t("综合顶尖","blue"),t("历史悠久","gold")],"description":"哈佛大学成立于1636年，QS 2025排名全球第4，在法学、医学、商学领域全球顶尖。"},
    {"id":2,"name":"Massachusetts Institute of Technology","cn":"麻省理工学院","loc":"美国","region":"北美","country":"美国","logo":"#8B1E1E","initials":"M","score":96.8,"trend":"up","trendV":"+0.5","stars":4.8,"reviews":2156,"rank":2,"metrics":m(99,98,76,92,98,98,79,99),"tags":[t("QS第1","gold"),t("理工强校","blue"),t("创新","green")],"description":"MIT QS 2025排名全球第1，工程、计算机、经济学均为世界顶级。"},
    {"id":3,"name":"Stanford University","cn":"斯坦福大学","loc":"美国","region":"北美","country":"美国","logo":"#8C1515","initials":"S","score":95.5,"trend":"up","trendV":"+0.2","stars":4.8,"reviews":1987,"rank":3,"metrics":m(97,96,85,91,96,96,92,98),"tags":[t("硅谷","blue"),t("QS第6","gold"),t("创业","green")],"description":"斯坦福QS 2025排名全球第6，硅谷心脏，计算机和商学世界领先。"},
    {"id":4,"name":"California Institute of Technology","cn":"加州理工学院","loc":"美国","region":"北美","country":"美国","logo":"#FF6C0C","initials":"C","score":94.0,"trend":"up","trendV":"+0.3","stars":4.7,"reviews":680,"rank":4,"metrics":m(95,94,70,85,94,94,70,92),"tags":[t("QS第10","gold"),t("袖珍精英","purple"),t("诺奖密度","blue")],"description":"Caltech QS 2025排名全球第10，仅300名本科生，诺奖密度全球最高。"},
    {"id":5,"name":"University of Chicago","cn":"芝加哥大学","loc":"美国","region":"北美","country":"美国","logo":"#800000","initials":"U","score":92.0,"trend":"steady","trendV":"0","stars":4.6,"reviews":1200,"rank":5,"metrics":m(95,90,78,86,93,91,82,88),"tags":[t("经济学","gold"),t("诺奖工厂","purple"),t("社科","blue")],"description":"芝加哥大学经济学全球第一，诺奖经济学奖得主最多。"},
    {"id":6,"name":"University of Pennsylvania","cn":"宾夕法尼亚大学","loc":"美国","region":"北美","country":"美国","logo":"#011F5B","initials":"P","score":91.5,"trend":"up","trendV":"+0.4","stars":4.6,"reviews":1380,"rank":6,"metrics":m(93,95,80,88,87,88,84,94),"tags":[t("沃顿商学院","gold"),t("藤校","purple"),t("商科","blue")],"description":"宾大沃顿商学院全美第一，金融和商学世界顶尖。"},
    {"id":7,"name":"Columbia University","cn":"哥伦比亚大学","loc":"美国","region":"北美","country":"美国","logo":"#B9D9EB","initials":"C","score":91.0,"trend":"steady","trendV":"0","stars":4.5,"reviews":1520,"rank":7,"metrics":m(94,91,76,90,89,88,80,90),"tags":[t("藤校","purple"),t("纽约","green"),t("新闻学","blue")],"description":"哥大纽约市中心，新闻学和国际关系全美顶尖。"},
    {"id":8,"name":"Yale University","cn":"耶鲁大学","loc":"美国","region":"北美","country":"美国","logo":"#00356B","initials":"Y","score":90.5,"trend":"steady","trendV":"0","stars":4.5,"reviews":1540,"rank":8,"metrics":m(92,88,85,87,88,88,86,88),"tags":[t("QS第23","gold"),t("藤校","purple"),t("法学","blue")],"description":"耶鲁法学院全美第一，住宿学院制营造亲密社区。"},
    {"id":9,"name":"Princeton University","cn":"普林斯顿大学","loc":"美国","region":"北美","country":"美国","logo":"#E77500","initials":"P","score":90.0,"trend":"up","trendV":"+0.2","stars":4.5,"reviews":980,"rank":9,"metrics":m(94,87,88,82,92,90,90,85),"tags":[t("藤校","purple"),t("数学","gold"),t("纯研究","blue")],"description":"普林斯顿以纯学术研究著称，数学和物理世界顶尖。"},
    {"id":10,"name":"Duke University","cn":"杜克大学","loc":"美国","region":"北美","country":"美国","logo":"#003087","initials":"D","score":88.5,"trend":"up","trendV":"+0.5","stars":4.4,"reviews":1260,"rank":10,"metrics":m(91,89,82,84,86,85,84,90),"tags":[t("南方哈佛","gold"),t("医学","blue"),t("篮球","green")],"description":"杜克大学医学和生物工程全美顶尖。"},
    {"id":11,"name":"Northwestern University","cn":"西北大学","loc":"美国","region":"北美","country":"美国","logo":"#4E2A84","initials":"N","score":87.5,"trend":"up","trendV":"+0.3","stars":4.4,"reviews":1100,"rank":11,"metrics":m(90,88,80,83,85,84,82,89),"tags":[t("传媒","gold"),t("Kellogg","blue"),t("综合","purple")],"description":"西北大学Medill新闻学院全美第一。"},
    {"id":12,"name":"Johns Hopkins University","cn":"约翰霍普金斯大学","loc":"美国","region":"北美","country":"美国","logo":"#002D72","initials":"J","score":87.0,"trend":"up","trendV":"+0.4","stars":4.4,"reviews":1150,"rank":12,"metrics":m(90,84,78,86,92,90,80,84),"tags":[t("医学","gold"),t("公共卫生","blue"),t("科研","purple")],"description":"JHU医学和公共卫生全美第一。"},
    {"id":13,"name":"UC Berkeley","cn":"加州大学伯克利","loc":"美国","region":"北美","country":"美国","logo":"#003262","initials":"B","score":86.5,"trend":"up","trendV":"+0.3","stars":4.3,"reviews":1680,"rank":13,"metrics":m(92,93,74,88,93,93,78,90),"tags":[t("QS第12","gold"),t("公立旗舰","blue"),t("CS强校","green")],"description":"UC Berkeley QS 2025排名全球第12，CS四大名校之一。"},
    {"id":14,"name":"Carnegie Mellon University","cn":"卡内基梅隆大学","loc":"美国","region":"北美","country":"美国","logo":"#C41230","initials":"C","score":86.0,"trend":"up","trendV":"+0.6","stars":4.3,"reviews":980,"rank":14,"metrics":m(90,94,72,87,89,88,76,95),"tags":[t("CS四大","gold"),t("AI先驱","blue"),t("机器人","green")],"description":"CMU计算机学院全美前三，AI和机器人领域世界领先。"},
    {"id":15,"name":"University of Michigan","cn":"密歇根大学","loc":"美国","region":"北美","country":"美国","logo":"#00274C","initials":"M","score":85.0,"trend":"up","trendV":"+0.4","stars":4.3,"reviews":1420,"rank":15,"metrics":m(89,90,78,82,87,86,80,88),"tags":[t("公立前3","gold"),t("工程","blue"),t("汽车城","green")],"description":"密歇根大学工程学院和商学院全美前10。"},
    {"id":16,"name":"New York University","cn":"纽约大学","loc":"美国","region":"北美","country":"美国","logo":"#57068C","initials":"N","score":84.5,"trend":"up","trendV":"+0.5","stars":4.3,"reviews":1560,"rank":16,"metrics":m(87,90,72,90,83,82,78,90),"tags":[t("纽约","green"),t("Stern","gold"),t("电影","blue")],"description":"NYU Stern商学院和Tisch艺术学院全美顶级。"},
    {"id":17,"name":"UCLA","cn":"加州大学洛杉矶","loc":"美国","region":"北美","country":"美国","logo":"#2774AE","initials":"U","score":84.0,"trend":"up","trendV":"+0.3","stars":4.2,"reviews":1750,"rank":17,"metrics":m(88,88,74,86,85,84,82,86),"tags":[t("公立双雄","gold"),t("好莱坞","green"),t("医学","blue")],"description":"UCLA加州公立双雄之一，电影和医学全美顶尖。"},
    {"id":18,"name":"Georgia Institute of Technology","cn":"佐治亚理工","loc":"美国","region":"北美","country":"美国","logo":"#B3A369","initials":"G","score":83.0,"trend":"up","trendV":"+0.7","stars":4.2,"reviews":920,"rank":18,"metrics":m(86,92,70,82,87,86,76,92),"tags":[t("工程","gold"),t("CS","blue"),t("性价比","green")],"description":"佐治亚理工工程学院全美前5。"},
    {"id":19,"name":"University of Southern California","cn":"南加州大学","loc":"美国","region":"北美","country":"美国","logo":"#990000","initials":"U","score":82.5,"trend":"up","trendV":"+0.3","stars":4.2,"reviews":1300,"rank":19,"metrics":m(85,88,74,84,82,81,80,88),"tags":[t("电影","gold"),t("LA","green"),t("工程","blue")],"description":"USC电影学院全美第一。"},
    {"id":20,"name":"University of Wisconsin-Madison","cn":"威斯康星麦迪逊","loc":"美国","region":"北美","country":"美国","logo":"#c5050c","initials":"W","score":81.0,"trend":"steady","trendV":"0","stars":4.1,"reviews":880,"rank":20,"metrics":m(86,84,76,78,85,84,80,82),"tags":[t("公立","blue"),t("科研","gold"),t("乳业","green")],"description":"威斯康星麦迪逊是公立研究型大学的典范。"},
    {"id":21,"name":"University of Texas at Austin","cn":"德州大学奥斯汀","loc":"美国","region":"北美","country":"美国","logo":"#BF5700","initials":"U","score":80.5,"trend":"up","trendV":"+0.5","stars":4.1,"reviews":1050,"rank":21,"metrics":m(85,86,74,78,84,83,78,86),"tags":[t("CS","blue"),t("石油","gold"),t("德州","green")],"description":"UT Austin计算机和石油工程全美顶尖。"},
    {"id":22,"name":"Boston University","cn":"波士顿大学","loc":"美国","region":"北美","country":"美国","logo":"#CC0000","initials":"B","score":79.5,"trend":"up","trendV":"+0.4","stars":4.0,"reviews":960,"rank":22,"metrics":m(83,82,72,84,80,79,78,84),"tags":[t("波士顿","green"),t("医学","blue"),t("传媒","gold")],"description":"波士顿大学地处学术重镇，医学和传播学实力雄厚。"},
    {"id":23,"name":"Purdue University","cn":"普渡大学","loc":"美国","region":"北美","country":"美国","logo":"#CFB991","initials":"P","score":79.0,"trend":"up","trendV":"+0.6","stars":4.0,"reviews":920,"rank":23,"metrics":m(84,86,72,78,83,82,76,88),"tags":[t("工程","gold"),t("航天","blue"),t("性价比","green")],"description":"普渡大学工程学院全美前10，航天工程极强。"},
    {"id":24,"name":"University of Illinois Urbana-Champaign","cn":"伊利诺伊香槟","loc":"美国","region":"北美","country":"美国","logo":"#E84A27","initials":"U","score":78.5,"trend":"up","trendV":"+0.4","stars":4.0,"reviews":1100,"rank":24,"metrics":m(85,86,72,80,84,83,78,86),"tags":[t("CS","gold"),t("工程","blue"),t("公立","green")],"description":"UIUC计算机学院全美前5。"},
    {"id":25,"name":"University of Washington","cn":"华盛顿大学","loc":"美国","region":"北美","country":"美国","logo":"#4B2E83","initials":"U","score":78.0,"trend":"up","trendV":"+0.5","stars":4.0,"reviews":980,"rank":25,"metrics":m(84,85,72,82,86,84,78,86),"tags":[t("CS","gold"),t("西雅图","green"),t("医学","blue")],"description":"UW计算机和医学全美前10。"},
    {"id":26,"name":"University of California, San Diego","cn":"加州大学圣地亚哥","loc":"美国","region":"北美","country":"美国","logo":"#182B49","initials":"U","score":77.5,"trend":"up","trendV":"+0.4","stars":4.0,"reviews":860,"rank":26,"metrics":m(83,82,74,84,85,83,78,82),"tags":[t("生物","gold"),t("海洋学","blue"),t("公立","green")],"description":"UCSD生物和海洋学全美顶尖。"},
    {"id":27,"name":"Rice University","cn":"莱斯大学","loc":"美国","region":"北美","country":"美国","logo":"#002469","initials":"R","score":77.0,"trend":"up","trendV":"+0.3","stars":4.0,"reviews":640,"rank":27,"metrics":m(85,82,82,78,82,80,84,84),"tags":[t("南方小藤","purple"),t("师生比","gold"),t("工程","blue")],"description":"莱斯大学小班精英教育，师生比极优。"},
    {"id":28,"name":"Vanderbilt University","cn":"范德堡大学","loc":"美国","region":"北美","country":"美国","logo":"#8E6F3E","initials":"V","score":76.5,"trend":"steady","trendV":"0","stars":4.0,"reviews":720,"rank":28,"metrics":m(83,80,80,76,78,77,82,82),"tags":[t("教育","gold"),t("南方","green"),t("医学","blue")],"description":"范德堡大学Peabody教育学院全美第一。"},
    {"id":29,"name":"University of Toronto","cn":"多伦多大学","loc":"加拿大","region":"北美","country":"加拿大","logo":"#00204E","initials":"U","score":86.0,"trend":"up","trendV":"+0.4","stars":4.3,"reviews":1450,"rank":29,"metrics":m(89,90,81,91,90,90,83,87),"tags":[t("QS第25","gold"),t("加拿大第一","purple"),t("AI","blue")],"description":"多伦多大学QS 2025排名全球第25，加拿大榜首。"},
    {"id":30,"name":"University of British Columbia","cn":"英属哥伦比亚大学","loc":"加拿大","region":"北美","country":"加拿大","logo":"#002145","initials":"U","score":82.0,"trend":"up","trendV":"+0.5","stars":4.1,"reviews":1120,"rank":30,"metrics":m(86,84,78,88,83,82,80,84),"tags":[t("加拿大第二","purple"),t("温哥华","green"),t("林业","gold")],"description":"UBC加拿大第二，温哥华最美校园。"},
    {"id":31,"name":"McGill University","cn":"麦吉尔大学","loc":"加拿大","region":"北美","country":"加拿大","logo":"#ED1B2D","initials":"M","score":80.0,"trend":"steady","trendV":"0","stars":4.0,"reviews":980,"rank":31,"metrics":m(85,82,76,86,82,81,78,82),"tags":[t("加拿大哈佛","purple"),t("医学","blue"),t("蒙特利尔","green")],"description":"麦吉尔大学加拿大顶尖，医学传统悠久。"},
    {"id":32,"name":"University of Waterloo","cn":"滑铁卢大学","loc":"加拿大","region":"北美","country":"加拿大","logo":"#FFD700","initials":"W","score":78.0,"trend":"up","trendV":"+0.8","stars":4.0,"reviews":860,"rank":32,"metrics":m(82,90,72,84,80,80,76,92),"tags":[t("Co-op","gold"),t("CS","blue"),t("就业","green")],"description":"滑铁卢大学Co-op带薪实习项目全北美最强。"},
]

# ==================== 欧洲 ====================
EU_UNIS = [
    {"id":33,"name":"University of Oxford","cn":"牛津大学","loc":"英国","region":"欧洲","country":"英国","logo":"#002147","initials":"O","score":94.5,"trend":"steady","trendV":"0","stars":4.7,"reviews":3120,"rank":33,"metrics":m(98,95,88,94,95,95,90,94),"tags":[t("QS第3","gold"),t("学院制","purple"),t("人文","blue")],"description":"牛津QS 2025排名全球第3，英语世界最古老大学。"},
    {"id":34,"name":"University of Cambridge","cn":"剑桥大学","loc":"英国","region":"欧洲","country":"英国","logo":"#106AB4","initials":"C","score":93.0,"trend":"steady","trendV":"0","stars":4.7,"reviews":2750,"rank":34,"metrics":m(97,94,86,93,94,94,91,93),"tags":[t("QS第5","gold"),t("科研","blue"),t("学院制","purple")],"description":"剑桥QS 2025排名全球第5，培养了120+诺贝尔奖得主。"},
    {"id":35,"name":"Imperial College London","cn":"帝国理工学院","loc":"英国","region":"欧洲","country":"英国","logo":"#003E74","initials":"I","score":90.2,"trend":"up","trendV":"+0.4","stars":4.5,"reviews":1650,"rank":35,"metrics":m(95,93,68,95,93,93,72,93),"tags":[t("QS第2","gold"),t("理工","blue"),t("伦敦","green")],"description":"帝国理工QS 2025排名全球第2，专注科学、工程、医学。"},
    {"id":36,"name":"ETH Zurich","cn":"苏黎世联邦理工","loc":"瑞士","region":"欧洲","country":"瑞士","logo":"#215CA8","initials":"E","score":91.8,"trend":"up","trendV":"+0.8","stars":4.6,"reviews":1520,"rank":36,"metrics":m(96,95,78,96,95,95,84,95),"tags":[t("QS第7","gold"),t("欧洲顶尖","green"),t("低成本","blue")],"description":"ETH QS 2025排名全球第7，爱因斯坦母校，年学费仅1500瑞郎。"},
    {"id":37,"name":"University College London","cn":"伦敦大学学院","loc":"英国","region":"欧洲","country":"英国","logo":"#500778","initials":"U","score":86.0,"trend":"up","trendV":"+0.3","stars":4.3,"reviews":1380,"rank":37,"metrics":m(89,84,72,92,86,85,78,84),"tags":[t("QS第9","gold"),t("多元","green"),t("教育","blue")],"description":"UCL QS 2025排名全球第9，伦敦市中心。"},
    {"id":38,"name":"London School of Economics","cn":"伦敦政治经济学院","loc":"英国","region":"欧洲","country":"英国","logo":"#D50032","initials":"L","score":85.0,"trend":"up","trendV":"+0.4","stars":4.3,"reviews":960,"rank":38,"metrics":m(88,90,70,94,84,82,76,92),"tags":[t("社科","gold"),t("金融","blue"),t("伦敦","green")],"description":"LSE社会科学全球顶尖，经济学和政治学世界前三。"},
    {"id":39,"name":"University of Edinburgh","cn":"爱丁堡大学","loc":"英国","region":"欧洲","country":"英国","logo":"#B30538","initials":"U","score":83.0,"trend":"up","trendV":"+0.3","stars":4.2,"reviews":1200,"rank":39,"metrics":m(86,82,76,88,84,82,80,82),"tags":[t("AI","gold"),t("历史","purple"),t("苏格兰","green")],"description":"爱丁堡大学AI和计算机全英前三。"},
    {"id":40,"name":"King's College London","cn":"伦敦国王学院","loc":"英国","region":"欧洲","country":"英国","logo":"#C8102E","initials":"K","score":81.5,"trend":"up","trendV":"+0.3","stars":4.1,"reviews":1080,"rank":40,"metrics":m(84,80,72,88,82,80,78,82),"tags":[t("医学","blue"),t("法学","gold"),t("伦敦","green")],"description":"KCL医学和法学全英前5。"},
    {"id":41,"name":"Technical University of Munich","cn":"慕尼黑工业大学","loc":"德国","region":"欧洲","country":"德国","logo":"#3070B3","initials":"T","score":81.8,"trend":"up","trendV":"+0.7","stars":4.1,"reviews":980,"rank":41,"metrics":m(88,87,79,86,87,87,81,88),"tags":[t("QS第28","gold"),t("德国顶尖","green"),t("免学费","blue")],"description":"TUM QS 2025排名全球第28，德国最强理工科。"},
    {"id":42,"name":"LMU Munich","cn":"慕尼黑大学","loc":"德国","region":"欧洲","country":"德国","logo":"#0064B4","initials":"L","score":80.0,"trend":"up","trendV":"+0.4","stars":4.0,"reviews":860,"rank":42,"metrics":m(86,80,78,84,83,82,80,80),"tags":[t("德国","green"),t("人文","purple"),t("免学费","blue")],"description":"LMU德国综合型大学标杆。"},
    {"id":43,"name":"Sorbonne University","cn":"索邦大学","loc":"法国","region":"欧洲","country":"法国","logo":"#1E4482","initials":"S","score":79.0,"trend":"steady","trendV":"0","stars":4.0,"reviews":1100,"rank":43,"metrics":m(88,84,76,85,84,84,82,80),"tags":[t("QS第63","gold"),t("人文","purple"),t("法国","green")],"description":"索邦大学传承欧洲最古老学术传统。"},
    {"id":44,"name":"University of Amsterdam","cn":"阿姆斯特丹大学","loc":"荷兰","region":"欧洲","country":"荷兰","logo":"#000000","initials":"U","score":78.5,"trend":"up","trendV":"+0.5","stars":4.0,"reviews":720,"rank":44,"metrics":m(84,82,74,88,82,81,78,82),"tags":[t("荷兰第一","purple"),t("心理学","gold"),t("商科","blue")],"description":"阿姆斯特丹大学荷兰排名第一，心理学和传播学极强。"},
    {"id":45,"name":"Delft University of Technology","cn":"代尔夫特理工","loc":"荷兰","region":"欧洲","country":"荷兰","logo":"#00A6D6","initials":"D","score":77.5,"trend":"up","trendV":"+0.6","stars":4.0,"reviews":680,"rank":45,"metrics":m(85,86,72,84,83,82,76,88),"tags":[t("工程","gold"),t("建筑","blue"),t("荷兰","green")],"description":"代尔夫特理工工程学院欧洲顶尖。"},
    {"id":46,"name":"Heidelberg University","cn":"海德堡大学","loc":"德国","region":"欧洲","country":"德国","logo":"#E6001F","initials":"H","score":76.5,"trend":"steady","trendV":"0","stars":4.0,"reviews":760,"rank":46,"metrics":m(84,78,76,82,80,79,80,78),"tags":[t("德国最老","purple"),t("医学","blue"),t("法学","gold")],"description":"海德堡大学德国最古老大学，医学和法学传统悠久。"},
    {"id":47,"name":"KU Leuven","cn":"鲁汶大学","loc":"比利时","region":"欧洲","country":"比利时","logo":"#8DBB4B","initials":"K","score":76.0,"trend":"up","trendV":"+0.4","stars":4.0,"reviews":620,"rank":47,"metrics":m(83,80,74,82,82,81,78,80),"tags":[t("比利时第一","purple"),t("工程","blue"),t("医学","gold")],"description":"鲁汶大学比利时排名第一。"},
    {"id":48,"name":"University of Zurich","cn":"苏黎世大学","loc":"瑞士","region":"欧洲","country":"瑞士","logo":"#0066CC","initials":"U","score":75.5,"trend":"up","trendV":"+0.3","stars":3.9,"reviews":580,"rank":48,"metrics":m(82,78,74,86,80,79,76,78),"tags":[t("瑞士","green"),t("商科","blue"),t("医学","gold")],"description":"苏黎世大学瑞士最大综合性大学。"},
    {"id":49,"name":"Politecnico di Milano","cn":"米兰理工大学","loc":"意大利","region":"欧洲","country":"意大利","logo":"#C5002F","initials":"P","score":75.0,"trend":"up","trendV":"+0.5","stars":3.9,"reviews":640,"rank":49,"metrics":m(84,86,70,78,80,80,74,86),"tags":[t("意大利第一","purple"),t("设计","gold"),t("建筑","blue")],"description":"米兰理工大学设计和建筑学欧洲顶尖。"},
    {"id":50,"name":"University of Manchester","cn":"曼彻斯特大学","loc":"英国","region":"欧洲","country":"英国","logo":"#660099","initials":"U","score":74.5,"trend":"up","trendV":"+0.3","stars":3.9,"reviews":1120,"rank":50,"metrics":m(83,80,72,84,80,79,76,80),"tags":[t("英国红砖","purple"),t("工程","blue"),t("商科","gold")],"description":"曼彻斯特大学英国红砖大学之一。"},
    {"id":51,"name":"University of Copenhagen","cn":"哥本哈根大学","loc":"丹麦","region":"欧洲","country":"丹麦","logo":"#901A1E","initials":"U","score":74.0,"trend":"steady","trendV":"0","stars":3.9,"reviews":520,"rank":51,"metrics":m(84,78,76,88,80,79,78,76),"tags":[t("丹麦第一","purple"),t("生命科学","gold"),t("北欧","green")],"description":"哥本哈根大学丹麦排名第一，生命科学极强。"},
    {"id":52,"name":"University of Bristol","cn":"布里斯托大学","loc":"英国","region":"欧洲","country":"英国","logo":"#00622E","initials":"U","score":73.5,"trend":"up","trendV":"+0.3","stars":3.8,"reviews":880,"rank":52,"metrics":m(82,78,74,80,78,77,76,80),"tags":[t("英国","purple"),t("工程","blue"),t("法学","gold")],"description":"布里斯托大学英国顶尖研究型大学。"},
    {"id":53,"name":"University of Warwick","cn":"华威大学","loc":"英国","region":"欧洲","country":"英国","logo":"#532E7D","initials":"W","score":73.0,"trend":"up","trendV":"+0.4","stars":3.8,"reviews":760,"rank":53,"metrics":m(81,82,72,82,78,77,74,84),"tags":[t("英国","purple"),t("商科","gold"),t("数学","blue")],"description":"华威大学商学院和数学系英国顶尖。"},
    {"id":54,"name":"Trinity College Dublin","cn":"都柏林圣三一","loc":"爱尔兰","region":"欧洲","country":"爱尔兰","logo":"#006341","initials":"T","score":72.5,"trend":"steady","trendV":"0","stars":3.8,"reviews":480,"rank":54,"metrics":m(82,76,74,88,76,75,76,76),"tags":[t("爱尔兰第一","purple"),t("人文","gold"),t("计算机","blue")],"description":"都柏林圣三一学院爱尔兰最古老大学。"},
    {"id":55,"name":"University of Glasgow","cn":"格拉斯哥大学","loc":"英国","region":"欧洲","country":"英国","logo":"#003865","initials":"U","score":72.0,"trend":"up","trendV":"+0.3","stars":3.8,"reviews":620,"rank":55,"metrics":m(81,76,72,84,76,75,76,76),"tags":[t("苏格兰","green"),t("医学","blue"),t("历史","purple")],"description":"格拉斯哥大学苏格兰第四古老大学。"},
]

# ==================== 亚洲 ====================
ASIA_UNIS = [
    {"id":56,"name":"National University of Singapore","cn":"新加坡国立","loc":"新加坡","region":"亚洲","country":"新加坡","logo":"#EF7C00","initials":"N","score":87.5,"trend":"up","trendV":"+0.6","stars":4.4,"reviews":1680,"rank":56,"metrics":m(91,90,84,94,90,90,88,92),"tags":[t("QS第8","gold"),t("亚洲之光","green"),t("国际化","purple")],"description":"NUS QS 2025排名全球第8，亚洲排名最高。"},
    {"id":57,"name":"Nanyang Technological University","cn":"南洋理工","loc":"新加坡","region":"亚洲","country":"新加坡","logo":"#0099DC","initials":"N","score":85.0,"trend":"up","trendV":"+0.5","stars":4.2,"reviews":1180,"rank":57,"metrics":m(89,88,76,92,86,85,80,90),"tags":[t("QS第11","gold"),t("工程","blue"),t("新加坡","green")],"description":"南洋理工QS 2025排名全球第11，工程学院亚洲顶尖。"},
    {"id":58,"name":"Tsinghua University","cn":"清华大学","loc":"北京","region":"亚洲","country":"中国","logo":"#660874","initials":"T","score":90.0,"trend":"up","trendV":"+1.2","stars":4.7,"reviews":3200,"rank":58,"metrics":m(95,92,75,73,92,92,82,94),"tags":[t("QS第20","gold"),t("中国第一","purple"),t("工科","blue")],"description":"清华大学QS 2025排名全球第20，中国排名最高。"},
    {"id":59,"name":"Peking University","cn":"北京大学","loc":"北京","region":"亚洲","country":"中国","logo":"#8B0000","initials":"P","score":88.5,"trend":"up","trendV":"+0.9","stars":4.6,"reviews":2980,"rank":59,"metrics":m(94,89,73,71,89,89,80,90),"tags":[t("QS第14","gold"),t("人文","purple"),t("综合","blue")],"description":"北京大学QS 2025排名全球第14，人文社科见长。"},
    {"id":60,"name":"University of Hong Kong","cn":"香港大学","loc":"中国香港","region":"亚洲","country":"中国","logo":"#006C4C","initials":"H","score":82.5,"trend":"up","trendV":"+0.2","stars":4.2,"reviews":1400,"rank":60,"metrics":m(86,84,72,93,84,84,74,88),"tags":[t("QS第17","gold"),t("国际化","purple"),t("金融","blue")],"description":"香港大学QS 2025排名全球第17，商科和法学亚洲顶尖。"},
    {"id":61,"name":"Chinese University of Hong Kong","cn":"香港中文大学","loc":"中国香港","region":"亚洲","country":"中国","logo":"#740C64","initials":"C","score":80.0,"trend":"up","trendV":"+0.3","stars":4.0,"reviews":1080,"rank":61,"metrics":m(85,80,74,90,80,79,76,82),"tags":[t("香港第二","purple"),t("人文","gold"),t("医学","blue")],"description":"香港中文大学以人文和医学见长。"},
    {"id":62,"name":"Hong Kong University of Science and Technology","cn":"香港科技大学","loc":"中国香港","region":"亚洲","country":"中国","logo":"#0066CC","initials":"H","score":79.0,"trend":"up","trendV":"+0.4","stars":4.0,"reviews":880,"rank":62,"metrics":m(84,86,70,88,82,81,74,88),"tags":[t("香港第三","purple"),t("商科","gold"),t("工程","blue")],"description":"香港科技大学商学院亚洲顶尖。"},
    {"id":63,"name":"University of Tokyo","cn":"东京大学","loc":"日本","region":"亚洲","country":"日本","logo":"#B51C1C","initials":"T","score":88.5,"trend":"steady","trendV":"0","stars":4.4,"reviews":2100,"rank":63,"metrics":m(93,92,70,68,92,92,76,90),"tags":[t("QS第32","gold"),t("日本第一","purple"),t("研究型","blue")],"description":"东京大学QS 2025排名全球第32，日本最高学府。"},
    {"id":64,"name":"Kyoto University","cn":"京都大学","loc":"日本","region":"亚洲","country":"日本","logo":"#5F4B8B","initials":"K","score":84.0,"trend":"up","trendV":"+0.3","stars":4.2,"reviews":1280,"rank":64,"metrics":m(90,84,72,66,88,87,74,84),"tags":[t("日本第二","purple"),t("物理","gold"),t("诺奖","blue")],"description":"京都大学日本诺奖得主最多的大学。"},
    {"id":65,"name":"Seoul National University","cn":"首尔大学","loc":"韩国","region":"亚洲","country":"韩国","logo":"#0F3370","initials":"S","score":78.0,"trend":"up","trendV":"+0.4","stars":4.0,"reviews":1250,"rank":65,"metrics":m(87,85,72,73,85,85,75,85),"tags":[t("QS第31","gold"),t("韩国第一","purple"),t("综合","blue")],"description":"首尔大学QS 2025排名全球第31，韩国最高学府。"},
    {"id":66,"name":"Korea Advanced Institute of Science and Technology","cn":"韩国科学技术院","loc":"韩国","region":"亚洲","country":"韩国","logo":"#0080FF","initials":"K","score":76.5,"trend":"up","trendV":"+0.6","stars":4.0,"reviews":680,"rank":66,"metrics":m(85,88,70,74,84,84,72,88),"tags":[t("韩国MIT","purple"),t("理工","gold"),t("科研","blue")],"description":"KAIST韩国理工科最高学府。"},
    {"id":67,"name":"Fudan University","cn":"复旦大学","loc":"上海","region":"亚洲","country":"中国","logo":"#005BAC","initials":"F","score":86.0,"trend":"up","trendV":"+0.6","stars":4.5,"reviews":2450,"rank":67,"metrics":m(92,87,74,69,87,87,79,89),"tags":[t("QS第39","gold"),t("上海","blue"),t("人文","purple")],"description":"复旦大学QS 2025排名全球第39，文理医三强。"},
    {"id":68,"name":"Zhejiang University","cn":"浙江大学","loc":"杭州","region":"亚洲","country":"中国","logo":"#174A8B","initials":"Z","score":85.5,"trend":"up","trendV":"+1.0","stars":4.5,"reviews":2300,"rank":68,"metrics":m(91,89,78,68,89,89,88,90),"tags":[t("QS第47","gold"),t("进步最快","green"),t("工科","blue")],"description":"浙江大学QS 2025排名全球第47，工科和计算机实力突出。"},
    {"id":69,"name":"Shanghai Jiao Tong University","cn":"上海交通大学","loc":"上海","region":"亚洲","country":"中国","logo":"#B3062D","initials":"S","score":84.8,"trend":"up","trendV":"+0.8","stars":4.4,"reviews":2180,"rank":69,"metrics":m(91,88,76,66,88,88,82,91),"tags":[t("QS第45","gold"),t("工科","blue"),t("医学院","purple")],"description":"上海交通大学QS 2025排名全球第45，工科和医学院均为国内顶尖。"},
    {"id":70,"name":"University of Science and Technology of China","cn":"中国科学技术大学","loc":"合肥","region":"亚洲","country":"中国","logo":"#00529B","initials":"U","score":84.0,"trend":"up","trendV":"+0.5","stars":4.4,"reviews":1650,"rank":70,"metrics":m(93,91,71,62,91,91,76,88),"tags":[t("科研","gold"),t("理科","blue"),t("精英","purple")],"description":"中科大以理科和前沿科研著称。"},
    {"id":71,"name":"Nanjing University","cn":"南京大学","loc":"南京","region":"亚洲","country":"中国","logo":"#1B3275","initials":"N","score":83.0,"trend":"steady","trendV":"0","stars":4.3,"reviews":1820,"rank":71,"metrics":m(91,86,76,63,86,86,83,85),"tags":[t("人文底蕴","gold"),t("天文","blue"),t("C9","purple")],"description":"南京大学以深厚人文底蕴见长。"},
    {"id":72,"name":"Wuhan University","cn":"武汉大学","loc":"武汉","region":"亚洲","country":"中国","logo":"#2C6E49","initials":"W","score":81.5,"trend":"up","trendV":"+0.4","stars":4.2,"reviews":2100,"rank":72,"metrics":m(88,84,80,60,84,84,92,83),"tags":[t("最美校园","green"),t("测绘","blue"),t("综合","purple")],"description":"武汉大学以樱花城堡闻名，测绘遥感全球顶尖。"},
    {"id":73,"name":"Huazhong University of Science and Technology","cn":"华中科技大学","loc":"武汉","region":"亚洲","country":"中国","logo":"#1A5276","initials":"H","score":81.0,"trend":"up","trendV":"+0.9","stars":4.2,"reviews":1950,"rank":73,"metrics":m(88,86,78,59,86,86,84,86),"tags":[t("工科","blue"),t("同济","green"),t("进步快","purple")],"description":"华中科技大学以工科著称，机械和光电全国顶尖。"},
    {"id":74,"name":"Sun Yat-sen University","cn":"中山大学","loc":"广州","region":"亚洲","country":"中国","logo":"#004422","initials":"S","score":80.5,"trend":"up","trendV":"+0.3","stars":4.2,"reviews":1880,"rank":74,"metrics":m(87,84,77,64,84,84,86,84),"tags":[t("华南第一","gold"),t("医学","blue"),t("大湾区","green")],"description":"中山大学华南地区最强高校。"},
    {"id":75,"name":"Harbin Institute of Technology","cn":"哈尔滨工业大学","loc":"哈尔滨","region":"亚洲","country":"中国","logo":"#003366","initials":"H","score":80.0,"trend":"up","trendV":"+0.6","stars":4.1,"reviews":1720,"rank":75,"metrics":m(87,86,73,58,86,86,73,87),"tags":[t("航天","gold"),t("工科","blue"),t("C9","purple")],"description":"哈工大航天工程全国第一。"},
    {"id":76,"name":"Xi'an Jiaotong University","cn":"西安交通大学","loc":"西安","region":"亚洲","country":"中国","logo":"#9B1B30","initials":"X","score":79.5,"trend":"up","trendV":"+0.5","stars":4.1,"reviews":1680,"rank":76,"metrics":m(87,85,73,60,85,85,77,85),"tags":[t("西部第一","gold"),t("电气","blue"),t("C9","purple")],"description":"西安交通大学电气工程全国顶尖。"},
    {"id":77,"name":"Tongji University","cn":"同济大学","loc":"上海","region":"亚洲","country":"中国","logo":"#003B5C","initials":"T","score":79.0,"trend":"up","trendV":"+0.3","stars":4.1,"reviews":1560,"rank":77,"metrics":m(86,84,74,67,84,84,80,86),"tags":[t("建筑","gold"),t("土木","blue"),t("上海","green")],"description":"同济大学建筑和土木工程全国顶级。"},
    {"id":78,"name":"Beijing Normal University","cn":"北京师范大学","loc":"北京","region":"亚洲","country":"中国","logo":"#0056A7","initials":"B","score":78.0,"trend":"steady","trendV":"0","stars":4.0,"reviews":1420,"rank":78,"metrics":m(86,82,75,64,82,82,75,82),"tags":[t("教育","gold"),t("心理","purple"),t("文科","blue")],"description":"北京师范大学教育学和心理学全国第一。"},
    {"id":79,"name":"Renmin University of China","cn":"中国人民大学","loc":"北京","region":"亚洲","country":"中国","logo":"#B22222","initials":"R","score":77.5,"trend":"steady","trendV":"0","stars":4.0,"reviews":1350,"rank":79,"metrics":m(85,80,72,63,80,80,72,86),"tags":[t("社科","gold"),t("京城四校","purple"),t("金融","blue")],"description":"中国人民大学人文社科全国第一。"},
    {"id":80,"name":"Nankai University","cn":"南开大学","loc":"天津","region":"亚洲","country":"中国","logo":"#741F7E","initials":"N","score":76.0,"trend":"up","trendV":"+0.3","stars":4.0,"reviews":1180,"rank":80,"metrics":m(84,80,74,60,80,80,76,80),"tags":[t("历史","gold"),t("经济","blue"),t("天津","green")],"description":"南开大学经济学和历史学全国顶尖。"},
    {"id":81,"name":"Tianjin University","cn":"天津大学","loc":"天津","region":"亚洲","country":"中国","logo":"#004EA2","initials":"T","score":75.5,"trend":"up","trendV":"+0.4","stars":3.9,"reviews":1020,"rank":81,"metrics":m(84,82,72,58,80,80,76,82),"tags":[t("工科","blue"),t("建筑","gold"),t("天津","green")],"description":"天津大学中国第一所现代大学。"},
    {"id":82,"name":"Shandong University","cn":"山东大学","loc":"济南","region":"亚洲","country":"中国","logo":"#003366","initials":"S","score":74.5,"trend":"up","trendV":"+0.3","stars":3.9,"reviews":1380,"rank":82,"metrics":m(82,78,74,56,78,78,76,78),"tags":[t("综合","purple"),t("历史","gold"),t("山东","green")],"description":"山东大学综合性研究型大学。"},
    {"id":83,"name":"Xiamen University","cn":"厦门大学","loc":"厦门","region":"亚洲","country":"中国","logo":"#003366","initials":"X","score":74.0,"trend":"up","trendV":"+0.3","stars":3.9,"reviews":1160,"rank":83,"metrics":m(82,78,74,62,78,78,78,78),"tags":[t("最美校园","green"),t("经济","blue"),t("厦门","purple")],"description":"厦门大学经济学院和会计学全国顶尖。"},
    {"id":84,"name":"Beijing Institute of Technology","cn":"北京理工大学","loc":"北京","region":"亚洲","country":"中国","logo":"#CC0000","initials":"B","score":73.5,"trend":"up","trendV":"+0.5","stars":3.8,"reviews":920,"rank":84,"metrics":m(83,84,70,58,80,80,72,84),"tags":[t("军工","gold"),t("工科","blue"),t("北京","green")],"description":"北京理工大学军工背景，工科实力雄厚。"},
    {"id":85,"name":"Jilin University","cn":"吉林大学","loc":"长春","region":"亚洲","country":"中国","logo":"#9B1B30","initials":"J","score":73.0,"trend":"steady","trendV":"0","stars":3.8,"reviews":1240,"rank":85,"metrics":m(82,76,72,54,76,76,76,76),"tags":[t("综合","purple"),t("法学","blue"),t("东北","green")],"description":"吉林大学东北地区综合性大学。"},
]

# ==================== 大洋洲 ====================
OCEANIA_UNIS = [
    {"id":86,"name":"University of Melbourne","cn":"墨尔本大学","loc":"澳大利亚","region":"大洋洲","country":"澳大利亚","logo":"#09416C","initials":"M","score":83.0,"trend":"up","trendV":"+0.5","stars":4.2,"reviews":1280,"rank":86,"metrics":m(87,86,84,89,86,86,88,85),"tags":[t("QS第13","gold"),t("澳洲第一","green"),t("宜居","purple")],"description":"墨尔本大学QS 2025排名全球第13，澳洲最高排名。"},
    {"id":87,"name":"University of Sydney","cn":"悉尼大学","loc":"澳大利亚","region":"大洋洲","country":"澳大利亚","logo":"#E87722","initials":"U","score":81.0,"trend":"up","trendV":"+0.4","stars":4.1,"reviews":1180,"rank":87,"metrics":m(85,84,78,86,82,82,82,84),"tags":[t("QS第18","gold"),t("澳洲第二","purple"),t("法学","blue")],"description":"悉尼大学QS 2025排名全球第18，澳洲最古老大学。"},
    {"id":88,"name":"Australian National University","cn":"澳大利亚国立","loc":"澳大利亚","region":"大洋洲","country":"澳大利亚","logo":"#BE8300","initials":"A","score":80.0,"trend":"steady","trendV":"0","stars":4.0,"reviews":860,"rank":88,"metrics":m(86,86,74,84,86,86,74,80),"tags":[t("QS第30","gold"),t("研究型","blue"),t("政策研究","purple")],"description":"ANU QS 2025排名全球第30，以研究为导向。"},
    {"id":89,"name":"University of Queensland","cn":"昆士兰大学","loc":"澳大利亚","region":"大洋洲","country":"澳大利亚","logo":"#512888","initials":"U","score":78.0,"trend":"up","trendV":"+0.4","stars":4.0,"reviews":780,"rank":89,"metrics":m(84,80,76,82,82,82,80,80),"tags":[t("澳洲八大","purple"),t("生物","blue"),t("布里斯班","green")],"description":"昆士兰大学生物和环境科学极强。"},
    {"id":90,"name":"Monash University","cn":"莫纳什大学","loc":"澳大利亚","region":"大洋洲","country":"澳大利亚","logo":"#006C54","initials":"M","score":76.5,"trend":"up","trendV":"+0.5","stars":3.9,"reviews":820,"rank":90,"metrics":m(82,82,74,84,80,80,76,84),"tags":[t("澳洲八大","purple"),t("商科","blue"),t("墨尔本","green")],"description":"莫纳什大学商学院澳洲顶尖。"},
    {"id":91,"name":"University of New South Wales","cn":"新南威尔士大学","loc":"澳大利亚","region":"大洋洲","country":"澳大利亚","logo":"#0055A5","initials":"U","score":77.5,"trend":"up","trendV":"+0.4","stars":4.0,"reviews":880,"rank":91,"metrics":m(84,86,72,86,82,82,76,88),"tags":[t("澳洲八大","purple"),t("工程","gold"),t("悉尼","green")],"description":"新南威尔士大学工程学院澳洲顶尖。"},
    {"id":92,"name":"University of Auckland","cn":"奥克兰大学","loc":"新西兰","region":"大洋洲","country":"新西兰","logo":"#004B8D","initials":"U","score":74.0,"trend":"up","trendV":"+0.3","stars":3.9,"reviews":540,"rank":92,"metrics":m(82,78,76,86,78,78,78,76),"tags":[t("新西兰第一","purple"),t("综合","blue"),t("奥克兰","green")],"description":"奥克兰大学新西兰排名第一。"},
]

# ==================== 其他地区 ====================
OTHER_UNIS = [
    {"id":93,"name":"King Saud University","cn":"沙特国王大学","loc":"沙特","region":"中东","country":"沙特阿拉伯","logo":"#006633","initials":"K","score":72.0,"trend":"up","trendV":"+0.5","stars":3.8,"reviews":420,"rank":93,"metrics":m(80,76,72,68,76,76,72,74),"tags":[t("中东第一","purple"),t("石油","blue"),t("沙特","green")],"description":"沙特国王大学中东地区顶尖大学。"},
    {"id":94,"name":"Tel Aviv University","cn":"特拉维夫大学","loc":"以色列","region":"中东","country":"以色列","logo":"#003399","initials":"T","score":75.0,"trend":"up","trendV":"+0.4","stars":3.9,"reviews":480,"rank":94,"metrics":m(83,80,74,74,82,82,72,78),"tags":[t("以色列第二","purple"),t("创新","gold"),t("CS","blue")],"description":"特拉维夫大学以色列创业中心。"},
    {"id":95,"name":"Hebrew University of Jerusalem","cn":"希伯来大学","loc":"以色列","region":"中东","country":"以色列","logo":"#FF6600","initials":"H","score":76.5,"trend":"up","trendV":"+0.3","stars":4.0,"reviews":520,"rank":95,"metrics":m(85,78,76,72,84,84,74,76),"tags":[t("以色列第一","purple"),t("诺奖","gold"),t("历史","blue")],"description":"希伯来大学以色列最高学府。"},
    {"id":96,"name":"University of Sao Paulo","cn":"圣保罗大学","loc":"巴西","region":"南美","country":"巴西","logo":"#FFD700","initials":"U","score":73.0,"trend":"up","trendV":"+0.4","stars":3.8,"reviews":680,"rank":96,"metrics":m(82,76,74,62,80,80,76,72),"tags":[t("南美第一","purple"),t("拉美","green"),t("综合","blue")],"description":"圣保罗大学拉丁美洲最高学府。"},
    {"id":97,"name":"Universidad de Buenos Aires","cn":"布宜诺斯艾利斯大学","loc":"阿根廷","region":"南美","country":"阿根廷","logo":"#75AADB","initials":"U","score":71.0,"trend":"up","trendV":"+0.3","stars":3.7,"reviews":560,"rank":97,"metrics":m(80,74,72,68,78,78,74,70),"tags":[t("阿根廷第一","purple"),t("南美","green"),t("人文","blue")],"description":"布宜诺斯艾利斯大学阿根廷最高学府。"},
    {"id":98,"name":"Cape Town University","cn":"开普敦大学","loc":"南非","region":"非洲","country":"南非","logo":"#003366","initials":"C","score":72.5,"trend":"up","trendV":"+0.3","stars":3.8,"reviews":420,"rank":98,"metrics":m(82,76,74,76,78,78,74,72),"tags":[t("非洲第一","purple"),t("医学","blue"),t("南非","green")],"description":"开普敦大学非洲最高学府。"},
    {"id":99,"name":"University of the Witwatersrand","cn":"威特沃特斯兰德大学","loc":"南非","region":"非洲","country":"南非","logo":"#003366","initials":"W","score":70.0,"trend":"steady","trendV":"0","stars":3.7,"reviews":320,"rank":99,"metrics":m(80,74,72,70,76,76,72,70),"tags":[t("南非第二","purple"),t("矿业","gold"),t("非洲","green")],"description":"威特沃特斯兰德大学南非矿业研究顶尖。"},
    {"id":100,"name":"Lomonosov Moscow State University","cn":"莫斯科国立大学","loc":"俄罗斯","region":"欧洲","country":"俄罗斯","logo":"#CC0000","initials":"L","score":74.5,"trend":"steady","trendV":"0","stars":3.9,"reviews":720,"rank":100,"metrics":m(83,76,76,62,80,80,76,72),"tags":[t("俄罗斯第一","purple"),t("数学","gold"),t("物理","blue")],"description":"莫斯科国立大学俄罗斯最高学府。"},
    {"id":101,"name":"St. Petersburg State University","cn":"圣彼得堡国立大学","loc":"俄罗斯","region":"欧洲","country":"俄罗斯","logo":"#000066","initials":"S","score":72.0,"trend":"up","trendV":"+0.3","stars":3.8,"reviews":480,"rank":101,"metrics":m(80,74,74,60,78,78,74,70),"tags":[t("俄罗斯第二","purple"),t("历史","gold"),t("文学","blue")],"description":"圣彼得堡国立大学普京母校。"},
]

# ==================== 英国补充 ====================
UK_MORE = [
    {"id":102,"name":"University of Glasgow","cn":"格拉斯哥大学","loc":"英国","region":"欧洲","country":"英国","logo":"#003865","initials":"U","score":72.0,"trend":"up","trendV":"+0.3","stars":3.8,"reviews":620,"rank":102,"metrics":m(81,76,72,84,76,75,76,76),"tags":[t("苏格兰","green"),t("医学","blue"),t("历史","purple")],"description":"格拉斯哥大学苏格兰第四古老大学。"},
    {"id":103,"name":"University of Birmingham","cn":"伯明翰大学","loc":"英国","region":"欧洲","country":"英国","logo":"#DC582A","initials":"U","score":71.5,"trend":"up","trendV":"+0.3","stars":3.7,"reviews":580,"rank":103,"metrics":m(80,76,72,78,74,74,76,78),"tags":[t("英国红砖","purple"),t("工程","blue"),t("商科","gold")],"description":"伯明翰大学英国红砖大学之一。"},
    {"id":104,"name":"University of Sheffield","cn":"谢菲尔德大学","loc":"英国","region":"欧洲","country":"英国","logo":"#FFD200","initials":"U","score":71.0,"trend":"up","trendV":"+0.2","stars":3.7,"reviews":540,"rank":104,"metrics":m(80,76,72,76,74,74,76,76),"tags":[t("英国红砖","purple"),t("工程","blue"),t("新闻","gold")],"description":"谢菲尔德大学工程学院全英顶尖。"},
    {"id":105,"name":"University of Leeds","cn":"利兹大学","loc":"英国","region":"欧洲","country":"英国","logo":"#592D82","initials":"U","score":70.5,"trend":"up","trendV":"+0.3","stars":3.7,"reviews":520,"rank":105,"metrics":m(79,76,72,78,74,74,76,76),"tags":[t("英国红砖","purple"),t("传媒","gold"),t("商科","blue")],"description":"利兹大学传媒学院全英顶尖。"},
    {"id":106,"name":"University of Nottingham","cn":"诺丁汉大学","loc":"英国","region":"欧洲","country":"英国","logo":"#006432","initials":"U","score":70.0,"trend":"up","trendV":"+0.2","stars":3.6,"reviews":480,"rank":106,"metrics":m(78,76,72,76,72,72,76,76),"tags":[t("英国","purple"),t("药学","gold"),t("商科","blue")],"description":"诺丁汉大学药学院全英顶尖。"},
    {"id":107,"name":"University of Southampton","cn":"南安普顿大学","loc":"英国","region":"欧洲","country":"英国","logo":"#880088","initials":"U","score":69.5,"trend":"up","trendV":"+0.3","stars":3.6,"reviews":460,"rank":107,"metrics":m(78,78,72,76,74,74,74,78),"tags":[t("英国","purple"),t("CS","blue"),t("工程","gold")],"description":"南安普顿大学计算机和工程全英前列。"},
    {"id":108,"name":"Queen Mary University of London","cn":"伦敦玛丽女王大学","loc":"英国","region":"欧洲","country":"英国","logo":"#000000","initials":"Q","score":68.5,"trend":"up","trendV":"+0.4","stars":3.6,"reviews":380,"rank":108,"metrics":m(77,74,72,78,72,72,74,74),"tags":[t("伦敦","green"),t("医学","blue"),t("法学","gold")],"description":"伦敦玛丽女王大学医学和法学全英前列。"},
]

# ==================== 美国补充 ====================
US_MORE = [
    {"id":109,"name":"Boston College","cn":"波士顿学院","loc":"美国","region":"北美","country":"美国","logo":"#8B0000","initials":"B","score":72.5,"trend":"up","trendV":"+0.3","stars":3.8,"reviews":420,"rank":109,"metrics":m(80,78,78,72,72,72,78,78),"tags":[t("波士顿","green"),t("商科","gold"),t("教育","blue")],"description":"波士顿学院商学院和教育学院全美前列。"},
    {"id":110,"name":"Brandeis University","cn":"布兰代斯大学","loc":"美国","region":"北美","country":"美国","logo":"#00308F","initials":"B","score":71.5,"trend":"up","trendV":"+0.2","stars":3.7,"reviews":280,"rank":110,"metrics":m(79,76,78,74,72,72,76,74),"tags":[t("波士顿","green"),t("文科","purple"),t("犹太","gold")],"description":"布兰代斯大学文科研究型大学。"},
    {"id":111,"name":"University of Rochester","cn":"罗切斯特大学","loc":"美国","region":"北美","country":"美国","logo":"#FFB300","initials":"U","score":72.0,"trend":"up","trendV":"+0.3","stars":3.7,"reviews":360,"rank":111,"metrics":m(80,78,74,76,76,76,72,78),"tags":[t("纽约州","green"),t("音乐","gold"),t("光学","blue")],"description":"罗切斯特大学音乐学院全美顶尖。"},
    {"id":112,"name":"Case Western Reserve University","cn":"凯斯西储大学","loc":"美国","region":"北美","country":"美国","logo":"#0A4E25","initials":"C","score":71.0,"trend":"up","trendV":"+0.4","stars":3.7,"reviews":320,"rank":112,"metrics":m(79,78,74,74,76,76,72,78),"tags":[t("俄亥俄","green"),t("医学","blue"),t("工程","gold")],"description":"凯斯西储大学医学院全美前列。"},
    {"id":113,"name":"Northeastern University","cn":"东北大学","loc":"美国","region":"北美","country":"美国","logo":"#CC0000","initials":"N","score":70.5,"trend":"up","trendV":"+0.6","stars":3.6,"reviews":420,"rank":113,"metrics":m(77,84,70,82,72,72,72,86),"tags":[t("波士顿","green"),t("Co-op","gold"),t("CS","blue")],"description":"东北大学Co-op项目全美最强之一。"},
    {"id":114,"name":"University of California, Davis","cn":"加州大学戴维斯","loc":"美国","region":"北美","country":"美国","logo":"#002855","initials":"U","score":71.5,"trend":"up","trendV":"+0.3","stars":3.7,"reviews":480,"rank":114,"metrics":m(79,78,74,78,76,76,78,76),"tags":[t("公立","blue"),t("农业","gold"),t("加州","green")],"description":"UC Davis农业和环境科学全美第一。"},
    {"id":115,"name":"University of California, Irvine","cn":"加州大学尔湾","loc":"美国","region":"北美","country":"美国","logo":"#0064A8","initials":"U","score":70.5,"trend":"up","trendV":"+0.4","stars":3.6,"reviews":420,"rank":115,"metrics":m(78,78,72,80,74,74,76,78),"tags":[t("公立","blue"),t("CS","gold"),t("加州","green")],"description":"UCI计算机和生物全美前列。"},
    {"id":116,"name":"Ohio State University","cn":"俄亥俄州立大学","loc":"美国","region":"北美","country":"美国","logo":"#BB0000","initials":"O","score":70.0,"trend":"up","trendV":"+0.3","stars":3.6,"reviews":580,"rank":116,"metrics":m(78,80,72,72,74,74,76,80),"tags":[t("公立","blue"),t("工程","gold"),t("体育","green")],"description":"俄亥俄州立大学工程学院全美前列。"},
    {"id":117,"name":"Penn State University","cn":"宾州州立大学","loc":"美国","region":"北美","country":"美国","logo":"#041E42","initials":"P","score":69.5,"trend":"up","trendV":"+0.3","stars":3.6,"reviews":540,"rank":117,"metrics":m(77,80,72,72,74,74,76,80),"tags":[t("公立","blue"),t("工程","gold"),t("体育","green")],"description":"宾州州立大学工程学院全美前列。"},
    {"id":118,"name":"University of Florida","cn":"佛罗里达大学","loc":"美国","region":"北美","country":"美国","logo":"#FA4616","initials":"U","score":70.0,"trend":"up","trendV":"+0.4","stars":3.6,"reviews":520,"rank":118,"metrics":m(78,80,72,74,74,74,76,80),"tags":[t("公立","blue"),t("农业","gold"),t("佛罗里达","green")],"description":"佛罗里达大学农业和药学全美前列。"},
    {"id":119,"name":"University of Maryland","cn":"马里兰大学","loc":"美国","region":"北美","country":"美国","logo":"#E03A3E","initials":"U","score":69.5,"trend":"up","trendV":"+0.3","stars":3.6,"reviews":460,"rank":119,"metrics":m(77,80,72,76,74,74,74,80),"tags":[t("公立","blue"),t("CS","gold"),t("DC","green")],"description":"马里兰大学计算机全美前列，毗邻华盛顿特区。"},
    {"id":120,"name":"Arizona State University","cn":"亚利桑那州立大学","loc":"美国","region":"北美","country":"美国","logo":"#8C1D40","initials":"A","score":68.0,"trend":"up","trendV":"+0.5","stars":3.5,"reviews":580,"rank":120,"metrics":m(75,82,70,78,72,72,76,84),"tags":[t("公立","blue"),t("创新","gold"),t("亚利桑那","green")],"description":"亚利桑那州立大学全美创新排名第一。"},
]

# 合并所有高校
UNIVERSITIES = NA_UNIS + EU_UNIS + ASIA_UNIS + OCEANIA_UNIS + OTHER_UNIS + UK_MORE + US_MORE

# 重新编号
for i, u in enumerate(UNIVERSITIES, 1):
    u["id"] = i

# ==================== 专业排名 ====================
PROGRAMS = [
    {"name":"计算机科学","icon":"💻","univs":[{"rank":1,"univ":"MIT","tier":"gold"},{"rank":2,"univ":"Stanford","tier":"gold"},{"rank":3,"univ":"Carnegie Mellon","tier":"silver"},{"rank":4,"univ":"UC Berkeley","tier":"silver"},{"rank":5,"univ":"Tsinghua","tier":"bronze"}]},
    {"name":"商科 & MBA","icon":"💼","univs":[{"rank":1,"univ":"Harvard","tier":"gold"},{"rank":2,"univ":"Stanford","tier":"gold"},{"rank":3,"univ":"Wharton","tier":"silver"},{"rank":4,"univ":"London Business School","tier":"silver"},{"rank":5,"univ":"INSEAD","tier":"bronze"}]},
    {"name":"工程学","icon":"⚙️","univs":[{"rank":1,"univ":"MIT","tier":"gold"},{"rank":2,"univ":"Stanford","tier":"gold"},{"rank":3,"univ":"ETH Zurich","tier":"silver"},{"rank":4,"univ":"Tsinghua","tier":"silver"},{"rank":5,"univ":"Cambridge","tier":"bronze"}]},
    {"name":"医学","icon":"🏥","univs":[{"rank":1,"univ":"Harvard","tier":"gold"},{"rank":2,"univ":"Oxford","tier":"gold"},{"rank":3,"univ":"Johns Hopkins","tier":"silver"},{"rank":4,"univ":"Cambridge","tier":"silver"},{"rank":5,"univ":"Stanford","tier":"bronze"}]},
    {"name":"法学","icon":"⚖️","univs":[{"rank":1,"univ":"Yale","tier":"gold"},{"rank":2,"univ":"Harvard","tier":"gold"},{"rank":3,"univ":"Oxford","tier":"silver"},{"rank":4,"univ":"Cambridge","tier":"silver"},{"rank":5,"univ":"Renmin","tier":"bronze"}]},
    {"name":"人文社科","icon":"📖","univs":[{"rank":1,"univ":"Oxford","tier":"gold"},{"rank":2,"univ":"Harvard","tier":"gold"},{"rank":3,"univ":"Sorbonne","tier":"silver"},{"rank":4,"univ":"Peking","tier":"silver"},{"rank":5,"univ":"Cambridge","tier":"bronze"}]},
]

# ==================== 论坛帖子 ====================
FORUM_POSTS = [
    {"id":1,"title":"MIT vs Stanford：哪所学校的心理健康支持更到位？","category":"心理健康","author":"硅谷码农","content":"<p>我在MIT读CS硕士，女朋友在Stanford读MBA。两校表面风光无限，但学生心理健康问题已成公开的秘密。</p><p><strong>MIT</strong>：几乎每个学生都经历过「post-pset depression」（作业提交后的崩溃期）。学校有MIT Mental Health & Counseling，但预约平均等待2-3周。</p><p><strong>Stanford</strong>：Duck Syndrome（表面悠然自得，底下疯狂扑腾）比MIT更隐蔽。硅谷创业文化让「失败」成了禁忌。</p><p>两校近年都加大了投入，但供给远跟不上需求。选校时，「谁更在乎你的心理健康」比「谁排名更高」更重要。</p>","views":2340,"tags":["MIT","Stanford","心理健康"],"time":now},
    {"id":2,"title":"欧洲大学的人文关怀真比美国强吗？我的牛津交换体验","category":"人文关怀","author":"OxfordBird","content":"<p>我在清华本科，现在牛津交换中。最大震撼不是学术而是「人被当人看」。</p><p>牛津学院制决定了你有自己的宿舍、食堂、图书馆。每个学生配tutor，每周1-on-1 tutorial，教授真的记住你是谁。</p><p>对比美国Top 20 — 虽然资源也很好，但更像「大规模生产精英」。欧洲大学的「小而精」模式对学生的人文关怀更到位。</p>","views":1860,"tags":["欧洲","人文","对比"],"time":now},
    {"id":3,"title":"清华学生的「内卷」到底是动力还是毒药？","category":"学术氛围","author":"清华老学长","content":"<p>毕业三年回头看清华，最想说的就是「内卷」。</p><p>清华学术氛围不可否认 — 图书馆永远满座、学分绩点到两位小数的较量。有人说这是「动力」，但更多人说这是「毒药」— 永远在比较，永远觉得自己不够好。</p><p>真实数据：清华本科生焦虑症发病率高于全国平均2-3倍。我们那届有个CS同学，GPA 3.8还觉得自己「完了」。</p><p>我的建议：进清华前想清楚你要什么。不要为了「赢」而丢掉自己。</p>","views":3220,"tags":["清华","内卷","学术"],"time":now},
    {"id":4,"title":"ETH Zurich PhD：高薪但孤独 — 一个中国留学生的坦白","category":"心理健康","author":"苏黎世的雪","content":"<p>ETH PhD工资在欧洲算顶薪 — 年薪约5万瑞士法郎（35万人民币），读博还能攒钱。但孤独感是真的。</p><p>苏黎世很美、很安全、很无聊。晚上8点街上基本没人。学德语是必须的，不学的话生活半径永远在English bubble里。</p><p>如果你考虑ETH PhD，建议：<strong>语言先行+主动社交</strong>，别指望资源自动找上你。</p>","views":1570,"tags":["ETH","PhD","留学"],"time":now},
    {"id":5,"title":"澳洲 vs 加拿大：哪个更适合留学生移民？","category":"就业发展","author":"移民规划师","content":"<p>收到很多私信问澳洲和加拿大留学移民怎么选，今天统一聊一下。</p><p><strong>加拿大</strong>：EE快速通道对本地学位有加分，毕业后工签PGWP最长3年。安省和BC省还有省提名。路径清晰但最近分数水涨船高。</p><p><strong>澳洲</strong>：485毕业生工签改革后本科2年硕士3年。技术移民189/190需要凑分。读紧缺专业（IT/工程/医护）优势明显。</p><p>核心区别：加拿大更看重本地经验，澳洲更看重职业评估和能力。建议先确定职业方向再选国家。</p>","views":1980,"tags":["澳洲","加拿大","移民"],"time":now},
    {"id":6,"title":"北大 vs 清华：谁的校园生活更「有温度」？","category":"校园生活","author":"五道口吃瓜","content":"<p>这话题太容易引战了，但作为两校都上过课的人（清华本科+北大交换），想说点真实的。</p><p><strong>北大</strong>：未名湖畔的三角地，五四操场夜跑，农园食堂的麻辣香锅。<br><strong>清华</strong>：紫荆操场的午夜足球，清芬园的炸鸡腿，六教通宵自习室。</p><p>各有各的温度，看你要什么。</p>","views":2890,"tags":["北大","清华","校园生活"],"time":now},
    {"id":7,"title":"帝国理工 vs ETH Zurich：欧洲理工双雄全方位对比","category":"学术氛围","author":"欧陆理工控","content":"<p>两者都自称欧洲第一理工，今天从学费、科研、就业、生活四个维度对比。</p><p><strong>学费</strong>：ETH每年约1500瑞士法郎，IC每年约£37,500国际生。ETH赢麻了。</p><p><strong>科研</strong>：ETH有21个诺奖得主，但不只老本 — 近年AI、量子计算投入巨大。IC在工程转化（industry collaboration）上更强。</p><p><strong>就业</strong>：伦敦 vs 苏黎世。IC毕业生留伦敦金融城/咨询居多。ETH毕业生可选瑞士本土（ABB、罗氏）或去慕尼黑/柏林。</p><p><strong>生活方式</strong>：伦敦灯红酒绿，苏黎世岁月静好。选哪个看你性格。</p>","views":2100,"tags":["帝国理工","ETH","对比"],"time":now},
    {"id":8,"title":"藤校光环褪色？非藤校但超强的「隐藏牛校」盘点","category":"就业发展","author":"留美十年","content":"<p>很多人非Ivy League不去，但美国有很多非藤校的教育质量完全不输。</p><p>① <strong>MIT</strong>：严格来说不是藤校，但在CS/工程上是毋庸置疑的王者。<br>② <strong>Stanford</strong>：不是藤校，但硅谷地位无人能撼。创业投资回报率全美第一。<br>③ <strong>Caltech</strong>：袖珍精英校，诺奖密度全球最高。<br>④ <strong>Duke</strong>：南方的哈佛，医学和生物工程顶级。<br>⑤ <strong>UChicago</strong>：经济学重镇，诺奖经济学奖制造机。</p><p>结论：排名≠适合你。重要的是项目匹配度和个人发展空间。</p>","views":4560,"tags":["藤校","选校","隐藏牛校"],"time":now},
]

# ==================== 论坛评论 ====================
FORUM_COMMENTS = [
    {"id":1,"post_id":1,"author":"斯坦福小透明","text":"身为Stanford人只能说太真实了。Duck Syndrome害人不浅，大家都不愿意承认自己struggle。","likes":28,"time":now},
    {"id":2,"post_id":1,"author":"MIT Beaver","text":"MIT这边firehose模式确实需要更强的心理承受力。但学校在改善，这两年新增了不少wellness program。","likes":19,"time":now},
    {"id":3,"post_id":1,"author":"哈佛路人甲","text":"Harvard这边也不轻松。Ivy League通病 — 外表光鲜，内在焦虑。关键是要找到support system。","likes":15,"time":now},
    {"id":4,"post_id":2,"author":"欧洲老博士","text":"同意！我在ETH读博5年，导师每周固定1h一对一讨论。相比美国实验室group meeting每周汇报的模式，欧洲给个人成长空间更大。","likes":34,"time":now},
    {"id":5,"post_id":2,"author":"北美打工人","text":"笑死，美国大学那种「resources are everywhere you just need to ask」的模式 — 问题是你得先知道自己需要问什么。","likes":22,"time":now},
    {"id":6,"post_id":3,"author":"清华2025","text":"正在经历这一切...看到学长的帖子感觉被理解了。我们都太擅长伪装「没事」了。","likes":47,"time":now},
    {"id":7,"post_id":3,"author":"北大er","text":"北大也一样。清北通病 — 因为太优秀所以更害怕失败。其实跳出来看，TOP2已经很好了。","likes":31,"time":now},
    {"id":8,"post_id":4,"author":"慕尼黑的雾","text":"TUM这边也差不多。德国大学的support其实不差，但你需要主动走出comfort zone。","likes":16,"time":now},
    {"id":9,"post_id":4,"author":"瑞士老油条","text":"来瑞士第三年了，说实话 — 适应期至少一年。之后会慢慢发现苏黎世的好。滑雪季来了你就不想走了。","likes":21,"time":now},
    {"id":10,"post_id":5,"author":"加拿大小土豆","text":"我在多伦多读的CS，毕业半年拿PR。加拿大对IT确实友好，但冬天真的要命。","likes":18,"time":now},
    {"id":11,"post_id":5,"author":"悉尼土著","text":"澳洲现在移民确实变难了，但生活质量没得说。建议英语好的冲189独立技术移民。","likes":12,"time":now},
    {"id":12,"post_id":6,"author":"未名湖的鱼","text":"北大的「温度」在于自由 — 你可以选任何你想上的课，去任何你想去的地方。这种自由在清华很难想象。","likes":38,"time":now},
    {"id":13,"post_id":6,"author":"清华工科狗","text":"作为清华人我必须说 — 我们也有自己的浪漫。凌晨三点的紫荆操场，和室友躺在草地上看星星。","likes":45,"time":now},
    {"id":14,"post_id":7,"author":"伦敦打工人","text":"IC毕业四年了。伦敦金融圈确实够大，但英国工签政策越来越不友好。后梅姨时代的痛。","likes":14,"time":now},
    {"id":15,"post_id":8,"author":"杜克蓝魔","text":"Duke终于被提到了！我们学校真的被underrated。医学院和Fuqua商学院都是顶级。","likes":25,"time":now},
    {"id":16,"post_id":8,"author":"Caltech苦行僧","text":"Caltech 300个本科生一届，比高中还小。教授认识每个人。但workload是我听过最恐怖的。","likes":33,"time":now},
]

# 12 种论坛分类
FORUM_CATEGORIES = ["学术氛围","校园生活","就业发展","心理健康","人文关怀","留学申请","专业选择","院校对比","奖学金","实习","研究生","博士"]
